### ISSUE TITLE
Issue with the App drawer and Keyboard

### ISSUE THREAD

**Issue by PraveenGongada** [caseyryan/flutter_focus_catcher#3]
Keyboard is getting triggered when app drawer is opened, 
To Fix this change the code in the lines 162 and 163 to the code below :

if (!currentFocus.hasPrimaryFocus &&
                        currentFocus.hasFocus) {
                      FocusManager.instance.primaryFocus!.unfocus();

I tested this and it worked,
Thank You,

**Comment by caseyryan** [comment]
What do you mean by "keyboard is getting triggered when app drawer is opened"? 
Can you provide some code example?

**Comment by PraveenGongada** [comment]
Sorry I cant provide the code RN but the issue is when I use the FocusWatcher Package to unfocus my textfield and then click on the app drawer icon the textfield is gaining focus and and keyboard is popping up, The change in the above message solved the issue.

**Comment by caseyryan** [comment]
I took a look at the solution you proposed and it doesn't  seem to be the correct one. It's more like a hack which might work by a magic. 
This class is pretty simple, it works by checking bounding boxes of text fields. If it triggers the keyboard this means your text field is higher than the button. 
P. S. I suggest that you use Unfocuser from my another package flutter_multi_formatter https://github.com/caseyryan/flutter_multi_formatter/blob/master/lib/utils/unfocuser.dart instead of this one if you only need to unfocus your text field

**Comment by PraveenGongada** [comment]
The Solution was given here : 
https://github.com/flutter/flutter/issues/54277#issuecomment-640998757
Thanks for clarifying

**Comment by caseyryan** [comment]
Ok, I see this bug is not really related to any package but to the flutter itself. I'll try to reproduce it and see if Unfocuser also can handle it
